### ISSUE TITLE
[Bug]: Both the schnet_dgl and the egnn_pyg example fail with ddp 

### ISSUE THREAD

**Issue by JonathanSchmidt1** [IntelLabs/matsciml#106]
### Expected behavior

The examples to run

### Actual behavior

Running with 4 nodes and 4 workers results in the stacktrace posted below.
My guess would be that this is the case due to lazy modules not being initialized in time.
It seems to be related to the discussion at the end of this issue https://github.com/Lightning-AI/pytorch-lightning/issues/13764
Adding a setup hook in the base model class fixes the training with num_workers=0

    def setup(self, stage):
        match stage:
            case 'fit':
                dataloader = self.trainer.datamodule.train_dataloader()
            case 'validate':
                dataloader = self.trainer.datamodule.val_dataloader()
            case 'test':
                dataloader = self.trainer.datamodule.test_dataloader()
            case 'predict':
                dataloader = self.trainer.datamodule.predict_dataloader()
        dummy_batch = next(iter(dataloader))
        self.forward(dummy_batch)

However I had a few more issues with the test. The IS2RE devset seems to contain pickled graphs that are not loaded properly when loaded with a newer dgl version. So I had to use e.g. the NOMAD dataset to test it. 
With higher numbers of workers I was also not able to get it to work yet.
```
/scratch/snx3000/jschmidt/envs/dgl_113/lib/python3.11/site-packages/torch/nn/modules/lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '
/scratch/snx3000/jschmidt/envs/dgl_113/lib/python3.11/site-packages/torch/nn/modules/lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '
/scratch/snx3000/jschmidt/envs/dgl_113/lib/python3.11/site-packages/torch/nn/modules/lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '
/scratch/snx3000/jschmidt/envs/dgl_113/lib/python3.11/site-packages/torch/nn/modules/lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/scratch/snx3000/jschmidt/envs/dgl_113/lib/python3.11/site-packages/pytorch_lightning/trainer/connectors/logger_connector/logger_connector.py:67: Starting from v1.9.0, `tensorboardX` has been removed as a dependency of the `pytorch_lightning` package, due to potential conflicts with other packages in the ML ecosystem. For this reason, `logger=True` will use `CSVLogger` as the default logger, unless the `tensorboard` or `tensorboardX` packages are found. Please `pip install lightning[extra]` or one of them to enable TensorBoard support by default
Running in `fast_dev_run` mode: will run the requested loop using 1000 batch(es). Logging and checkpointing is suppressed.
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/4
Initializing distributed: GLOBAL_RANK: 2, MEMBER: 3/4
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/4
Initializing distributed: GLOBAL_RANK: 3, MEMBER: 4/4
[W socket.cpp:426] [c10d] The server socket cannot be initialized on [::]:15837 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [nid04102]:15837 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [nid04102]:15837 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [nid04102]:15837 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [nid04102]:15837 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [nid04102]:15837 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [nid04102]:15837 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [nid04102]:15837 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [nid04102]:15837 (errno: 97 - Address family not supported by protocol).
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 4 processes
----------------------------------------------------------------------------------------------------

libibverbs: Could not locate libibgni (/usr/lib64/libibgni.so.1: undefined symbol: verbs_uninit_context)
libibverbs: Warning: couldn't open config directory '/opt/cray/rdma-core/27.1-7.0.3.1_4.6__g4beae6eb.ari/etc/libibverbs.d'.
libibverbs: Could not locate libibgni (/usr/lib64/libibgni.so.1: undefined symbol: verbs_uninit_context)
libibverbs: Warning: couldn't open config directory '/opt/cray/rdma-core/27.1-7.0.3.1_4.6__g4beae6eb.ari/etc/libibverbs.d'.
libibverbs: Could not locate libibgni (/usr/lib64/libibgni.so.1: undefined symbol: verbs_uninit_context)
libibverbs: Could not locate libibgni (/usr/lib64/libibgni.so.1: undefined symbol: verbs_uninit_context)
libibverbs: Warning: couldn't open config directory '/opt/cray/rdma-core/27.1-7.0.3.1_4.6__g4beae6eb.ari/etc/libibverbs.d'.
libibverbs: Warning: couldn't open config directory '/opt/cray/rdma-core/27.1-7.0.3.1_4.6__g4beae6eb.ari/etc/libibverbs.d'.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Traceback (most recent call last):
  File "/scratch/snx3000/jschmidt/mirror/schnet/schnet_dgl.py", line 32, in <module>
Traceback (most recent call last):
  File "/scratch/snx3000/jschmidt/mirror/schnet/schnet_dgl.py", line 32, in <module>
Traceback (most recent call last):
  File "/scratch/snx3000/jschmidt/mirror/schnet/schnet_dgl.py", line 32, in <module>
    trainer.fit(task, datamodule=dm)
  File "/scratch/snx3000/jschmidt/envs/dgl_113/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 544, in fit
Traceback (most recent call last):
  File "/scratch/snx3000/jschmidt/mirror/schnet/schnet_dgl.py", line 32, in <module>
    trainer.fit(task, datamodule=dm)
  File "/scratch/snx3000/jschmidt/envs/dgl_113/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 544, in fit
    trainer.fit(task, datamodule=dm)
  File "/scratch/snx3000/jschmidt/envs/dgl_113/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 544, in fit
    trainer.fit(task, datamodule=dm)
  File "/scratch/snx3000/jschmidt/envs/dgl_113/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/scratch/snx3000/jschmidt/envs/dgl_113/lib/python3.11/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    call._call_and_handle_interrupt(
  File "/scratch/snx3000/jschmidt/envs/dgl_113/lib/python3.11/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    call._call_and_handle_interrupt(
  File "/scratch/snx3000/jschmidt/envs/dgl_113/lib/python3.11/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    call._call_and_handle_interrupt(
  File "/scratch/snx3000/jschmidt/envs/dgl_113/lib/python3.11/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/snx3000/jschmidt/envs/dgl_113/lib/python3.11/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 102, in launch
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/snx3000/jschmidt/envs/dgl_113/lib/python3.11/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 102, in launch
  File "/scratch/snx3000/jschmidt/envs/dgl_113/lib/python3.11/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 102, in launch
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/snx3000/jschmidt/envs/dgl_113/lib/python3.11/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 102, in launch
    return function(*args, **kwargs)
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
    return function(*args, **kwargs)
  File "/scratch/snx3000/jschmidt/envs/dgl_113/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 580, in _fit_impl
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/snx3000/jschmidt/envs/dgl_113/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 580, in _fit_impl
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/snx3000/jschmidt/envs/dgl_113/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 580, in _fit_impl
  File "/scratch/snx3000/jschmidt/envs/dgl_113/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/scratch/snx3000/jschmidt/envs/dgl_113/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 965, in _run
    self._run(model, ckpt_path=ckpt_path)
    self._run(model, ckpt_path=ckpt_path)
    self._run(model, ckpt_path=ckpt_path)
  File "/scratch/snx3000/jschmidt/envs/dgl_113/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 965, in _run
  File "/scratch/snx3000/jschmidt/envs/dgl_113/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 965, in _run
  File "/scratch/snx3000/jschmidt/envs/dgl_113/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 965, in _run
    self.strategy.setup(self)
    self.strategy.setup(self)
    self.strategy.setup(self)
  File "/scratch/snx3000/jschmidt/envs/dgl_113/lib/python3.11/site-packages/pytorch_lightning/strategies/ddp.py", line 169, in setup
    self.strategy.setup(self)
  File "/scratch/snx3000/jschmidt/envs/dgl_113/lib/python3.11/site-packages/pytorch_lightning/strategies/ddp.py", line 169, in setup
  File "/scratch/snx3000/jschmidt/envs/dgl_113/lib/python3.11/site-packages/pytorch_lightning/strategies/ddp.py", line 169, in setup
  File "/scratch/snx3000/jschmidt/envs/dgl_113/lib/python3.11/site-packages/pytorch_lightning/strategies/ddp.py", line 169, in setup
    self.configure_ddp()
    self.configure_ddp()
    self.configure_ddp()
    self.configure_ddp()
  File "/scratch/snx3000/jschmidt/envs/dgl_113/lib/python3.11/site-packages/pytorch_lightning/strategies/ddp.py", line 278, in configure_ddp
  File "/scratch/snx3000/jschmidt/envs/dgl_113/lib/python3.11/site-packages/pytorch_lightning/strategies/ddp.py", line 278, in configure_ddp
  File "/scratch/snx3000/jschmidt/envs/dgl_113/lib/python3.11/site-packages/pytorch_lightning/strategies/ddp.py", line 278, in configure_ddp
  File "/scratch/snx3000/jschmidt/envs/dgl_113/lib/python3.11/site-packages/pytorch_lightning/strategies/ddp.py", line 278, in configure_ddp
    self.model = self._setup_model(self.model)
    self.model = self._setup_model(self.model)
    self.model = self._setup_model(self.model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/snx3000/jschmidt/envs/dgl_113/lib/python3.11/site-packages/pytorch_lightning/strategies/ddp.py", line 191, in _setup_model
    self.model = self._setup_model(self.model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/snx3000/jschmidt/envs/dgl_113/lib/python3.11/site-packages/pytorch_lightning/strategies/ddp.py", line 191, in _setup_model
  File "/scratch/snx3000/jschmidt/envs/dgl_113/lib/python3.11/site-packages/pytorch_lightning/strategies/ddp.py", line 191, in _setup_model
  File "/scratch/snx3000/jschmidt/envs/dgl_113/lib/python3.11/site-packages/pytorch_lightning/strategies/ddp.py", line 191, in _setup_model
    return DistributedDataParallel(module=model, device_ids=device_ids, **self._ddp_kwargs)
    return DistributedDataParallel(module=model, device_ids=device_ids, **self._ddp_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return DistributedDataParallel(module=model, device_ids=device_ids, **self._ddp_kwargs)
    return DistributedDataParallel(module=model, device_ids=device_ids, **self._ddp_kwargs)
  File "/scratch/snx3000/jschmidt/envs/dgl_113/lib/python3.11/site-packages/torch/nn/parallel/distributed.py", line 656, in __init__
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/snx3000/jschmidt/envs/dgl_113/lib/python3.11/site-packages/torch/nn/parallel/distributed.py", line 656, in __init__
  File "/scratch/snx3000/jschmidt/envs/dgl_113/lib/python3.11/site-packages/torch/nn/parallel/distributed.py", line 656, in __init__
  File "/scratch/snx3000/jschmidt/envs/dgl_113/lib/python3.11/site-packages/torch/nn/parallel/distributed.py", line 656, in __init__
    self._log_and_throw(
  File "/scratch/snx3000/jschmidt/envs/dgl_113/lib/python3.11/site-packages/torch/nn/parallel/distributed.py", line 769, in _log_and_throw
    self._log_and_throw(
  File "/scratch/snx3000/jschmidt/envs/dgl_113/lib/python3.11/site-packages/torch/nn/parallel/distributed.py", line 769, in _log_and_throw
    self._log_and_throw(
  File "/scratch/snx3000/jschmidt/envs/dgl_113/lib/python3.11/site-packages/torch/nn/parallel/distributed.py", line 769, in _log_and_throw
    self._log_and_throw(
    raise err_type(err_msg)
RuntimeError: Modules with uninitialized parameters can't be used with `DistributedDataParallel`. Run a dummy forward pass to correctly initialize the modules
  File "/scratch/snx3000/jschmidt/envs/dgl_113/lib/python3.11/site-packages/torch/nn/parallel/distributed.py", line 769, in _log_and_throw
    raise err_type(err_msg)
RuntimeError: Modules with uninitialized parameters can't be used with `DistributedDataParallel`. Run a dummy forward pass to correctly initialize the modules
    raise err_type(err_msg)
RuntimeError: Modules with uninitialized parameters can't be used with `DistributedDataParallel`. Run a dummy forward pass to correctly initialize the modules
    raise err_type(err_msg)
RuntimeError: Modules with uninitialized parameters can't be used with `DistributedDataParallel`. Run a dummy forward pass to correctly initialize the modules
srun: error: nid04103: task 1: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=51280837.0
srun: error: nid04104: task 2: Exited with exit code 1
srun: error: nid04105: task 3: Exited with exit code 1
srun: error: nid04102: task 0: Exited with exit code 1

```

### Steps to reproduce the problem

run the schnet_dgl or egnn_pyg example on multiple nodes

### Specifications

torch.__version__
'2.0.0+cu118'
dgl.__version__
'1.1.3+cu118'
matsciml.__version__
'1.1.0'
torch_geometric.__version__
'2.3.1'

**Comment by laserkelvin** [comment]
You're right in that DDP doesn't work with lazy modules, which are the default layers used in `OutputBlock`. You can use `output_kwargs` in your task definition and pass `{"input_dim": ..., "lazy": False}` as shown in [this example](https://github.com/IntelLabs/matsciml/blob/1ea9e7723bcc23f37ed1da7bde332d6249d8af04/examples/model_demos/faenet_pyg.py#L30) to disable the lazy behavior, which is my preferred way of getting around this. 

I used lazy modules to help speed up model prototyping but obviously doesn't capture distributed use cases: I'm open to discussing whether this is a reasonable default behavior. Maybe not-lazy just needs to be better documented?

RE: the changes you've added I believe are Python 3.10+ since it uses match-case, so if we want to incorporate something like that we can just rewrite as old fashioned `if/else` statements. I think the patch is helpful if we want to keep lazy modules as default, and we could have `BaseTaskModule.setup` do it as mentioned in the discussions you linked. I would suggest something that looks like this:

```python
class BaseTaskModule(pl.LightningModule):
    def setup(self, stage: str):
        # check if we have any lazy modules
        has_lazy = any([isinstance(layer, nn.modules.lazy.LazyModuleMixin) for layer in self.modules])
        # only trigger these checks if we have lazy modules
        if has_lazy:
            for layer in self.modules:
                # if we have any layers that are uninitialized, we do the dummy forward run
                if isinstance(layer, nn.modules.lazy.LazyModuleMixin) and layer.has_uninitialized_params():
                     # setup dataloaders and do the dummy batch stuff
                     with torch.no_grad(): ...
```

Just as a side note, you mentioned 4 nodes and 4 workers and I wanted to confirm you intended to run one GPU per node?

**Comment by JonathanSchmidt1** [comment]
Oops I missed that `{"input_dim": ..., "lazy": False}`. I guess I have no strong opinion on whether to introduce a patch that automatically fixes it or whether to keep the `"lazy":` False option.  In the latter case an extra warning would be great so people don't end up like me trying to fix it.

> Just as a side note, you mentioned 4 nodes and 4 workers and I wanted to confirm you intended to run one GPU per node?

I have only nodes with one gpu each right now. However, concerning workers I was talking about the number of workers for each dataloader. So 4 gpu workers with 4 dataloading processes each for example.
